version: "2.8"

services:
  postgres:
    image: postgres:latest
    container_name: web_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "web"
    volumes:
      - pg_web_data:/var/lib/postgresql/data

volumes:
  pg_web_data:
