"""Initial migration

Revision ID: 0a2195c73602
Revises: 
Create Date: 2023-05-25 12:10:25.665051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2195c73602'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neural_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neural',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('tasks', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('short_desc', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['neural_category.id'], ),
    sa.PrimaryKeyConstraint('slug'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neural')
    op.drop_table('neural_category')
    # ### end Alembic commands ###
